Repository andsfonseca/term-cli, pull requests merged in 2022-02, with the labels that each got.

#1 Reparo no salvamento das estatísticas
  dist/game.js
  src/game.ts
Labels: bug

#2 Dicas do jogo e resolução de bugs
  dist/game.js
  dist/view.js
  package-lock.json
  src/game.ts
  src/view.ts
Labels: bug, enhancement

#5 Corrigido bug das estatísticas
  dist/game.js
  src/game.ts
Labels: bug

#6 Adicionada geração de palavra aleatória
  dist/game.js
  dist/index.js
  package-lock.json
  src/game.ts
  src/index.ts
Labels: enhancement
